### ISSUE TITLE
Object is not extensible when using minified version

### ISSUE THREAD

**Issue by smiffy6969** [GoogleChrome/proxy-polyfill#12]
When using minified version, I get a an error 'Object is not extensible' when trying to push or splice to an array.... if I Array.isArray() from console, the result is false..... strange.....

If I switch back to non minified, the issue goes away.

Anyone else noticed this?

**Comment by samthor** [comment]
If you proxy an array, it will always be made immutable (i.e., sealed).

When _your_ code is in strict mode, you'll get a `TypeError` when you try to modify that array. If you're not in strict mode, it'll fail silently (not good). Is your calling code in strict mode?

**Comment by smiffy6969** [comment]
No I am proxying an object with various properties, one property is an array. When I try to push or splice a value to the property, I get this error on the minified version.

I am not calling in strict mode.

Regardless of this, working in non minified and not working in minified kinda says..... These two things are not working the same, do they not?

Paul

**Comment by samthor** [comment]
I had a go at trying to [repro this here](https://github.com/GoogleChrome/proxy-polyfill/commit/2479dd90ed580f0bee9488b4d10477a49007968b). I then loaded the tests in Safari (uses minified, due to lack of ES6 support) and Chrome (non-minified) and they both pass.

Can you attach concise repro code or modify what I've written there?

**Comment by smiffy6969** [comment]
`export default class Observer {
	static object(obj, fn, deep, prefix) {
		if (typeof this.object === 'undefined') this.object = obj;
		prefix = typeof prefix === 'undefined' ? '' : prefix;
		return new Proxy(obj, {
			set: function(target, prop, value) {
				let old = target[prop];
				target[prop] = value;
				fn(prefix + prop, old, value);
				return true;
			},
			get: function(target, prop) {
				let val = target[prop];
				console.log(target, prop, typeof target);
				if (!!deep && val instanceof Object && typeof prop === 'string') return Observer.object(val, fn, deep, prefix + prop + '.');
				return val;
			}
		});
	}
}
`

The above is used to loop through object data to create a tree of observable objects, forcing a function to be run on change to any bit of the data.

This works fine with non minified version, but fails with minified version (sealed array elements on splice, not extensible on push). Like i say works like a dream on non minified.

While I am here, the more worrying thing here is that I am using chrome, I just completely removed the polyfill, and it works natively too with no problem. I just added the minified version back in, and it's not working...... surely, isn't the polyfill suppose to step back when there is native support, thats the whole point of a polyfill isn't it? I have no way of checking if the non minified version of this code is stepping back or not, but it clearly looks like the minifed version is being used regardless of browser having native or not.

So first, the nested observing on minified is failing, (my dirty tests look like not all changes are being picked up on minifed) but I do not know this library enough yet to comment.

Next, why is the minifed version failing anyway in chrome Version 50.0.2661.86 (64-bit)? surely native support stops the polyfill being loaded, replacing native support?

thanks

**Comment by samthor** [comment]
Ok, this was actually a bug: Closure compiler was clobbering the initial `scope.Proxy` check. I've fixed this now and [released a new version](https://github.com/GoogleChrome/proxy-polyfill/releases/tag/v0.1.4). Thanks for the report!

Having said that, your code is proxying each `Array` object too. And where there's no native support, this will make the array immutable- the polyfill can't treat these specially. For broad browser support, your best bet is to replace the whole array every time you want to change it.

**Comment by smiffy6969** [comment]
Ok thanks, still doesn't really explain why the non minified version works and the minified does not... I derived that code from reading the readme, the nested proxy bit. If this makes the Array object immutable, why does it work for non minified?

I have forked the code, I will play with this later and see what I come up with, but I still cannot get my head round the non-minified working differently to the minified, which appears to be creating arrays slightly differently, having tested the array with Array.isArray(). If nested binds do not work, why are they in the readme?

thanks

Paul

**Comment by smiffy6969** [comment]
Hi,

So I thought I would, first things first, minify the polyfill, as a sanity check I tried to use uglify (atom editor, node-uglify) to see if I get the same issue when I use a version i am minifying... guess what, I can't minify the proxy.js file, I get the following error in atom console...

```
JS_Parse_Error {message: "Unexpected token: name (lastRevokeFn)", filename: 0, line: 24, col: 6, pos: 695…}
col: 6
filename: 0
line: 24
message: "Unexpected token: name (lastRevokeFn)"
pos: 695
stack: "Error
at new JS_Parse_Error (evalmachine.<anonymous>:1525:18)
at js_error (evalmachine.<anonymous>:1533:11)
at croak (evalmachine.<anonymous>:2025:9)
at token_error (evalmachine.<anonymous>:2033:9)
at unexpected (evalmachine.<anonymous>:2039:9)
at semicolon (evalmachine.<anonymous>:2059:56)
at simple_statement (evalmachine.<anonymous>:2239:73)
at evalmachine.<anonymous>:2112:19
at evalmachine.<anonymous>:2072:24
at block_ (evalmachine.<anonymous>:2352:20)
at evalmachine.<anonymous>:2325:25
at function_ (evalmachine.<anonymous>:2330:15)
at expr_atom (evalmachine.<anonymous>:2545:24)
at maybe_unary (evalmachine.<anonymous>:2715:19)
at expr_ops (evalmachine.<anonymous>:2750:24)
at maybe_conditional (evalmachine.<anonymous>:2755:20)
at maybe_assign (evalmachine.<anonymous>:2779:20)
at expression (evalmachine.<anonymous>:2798:20)
at expr_atom (evalmachine.<anonymous>:2531:26)
at maybe_unary (evalmachine.<anonymous>:2715:19)
at expr_ops (evalmachine.<anonymous>:2750:24)
at maybe_conditional (evalmachine.<anonymous>:2755:20)
at maybe_assign (evalmachine.<anonymous>:2779:20)
at expression (evalmachine.<anonymous>:2798:20)
at simple_statement (evalmachine.<anonymous>:2239:55)
at evalmachine.<anonymous>:2124:24
at evalmachine.<anonymous>:2072:24
at evalmachine.<anonymous>:2826:23
at Object.parse (evalmachine.<anonymous>:2836:7)
at /home/paul/.atom/packages/uglify/node_modules/uglify-js/tools/node.js:64:33"
__proto__: JS_Parse_Error
```

I will keep looking, but this looks to me like a bad minification.

**Comment by smiffy6969** [comment]
I just did a quick dirty check working through the errors in when trying to uglify the code, removing the let's and replacing with var's and also swapping backticks for single quotes.....

I can get it to compile, and it works just like the non minified, no problem adding or removing array items using the nested method (just like native Proxy).

You really need to check over the minification, I had to butcher this file just to minify it. Why is let being used anyway in a polyfill? there are changes are they not to how it scopes in ES5? Plus using backticks (template literals) is a bit of a gamble is it not for a polyfill?

Is this because this polyfill is aiming at evergreen pretty much? I cannot get it to compile naturally (maybe some flags would help) but I can get this to work fine by changing these things, and it functions the same as the non minifed. 

So my question is, as the minified and non minified do not work the same, and I cannot compile proxy.js naturally, but changing it makes it compile and work as per native Proxy, does this not kinda show we need to adjust something somewhere?

thanks for your effort.

Paul

**Comment by smiffy6969** [comment]
Ok,

So after a lot of playing around, I finally see what is happening...

This bug with Proxy always being overriden when minified was actually also the reason why it was 'appearing to work' for me when using the non minified (was actually falling back to native, which allows nested Proxies) but the minified version was hard overriding the native proxy, meaning the nested was failing. Makes sense now, ignore the pull request.

I see this issue is now resolved as per things working differently between non minified and minified.

Lastly then, before i go (thanks for being patient by the way)... Is there no way to get nested proxies working ala native, or is this just not possible? I understand 'just replace the whole array' as a response, just wanting to know if I am going to be busting a nut here trying to get this to work a little more closely to native.

thanks

Paul

**Comment by smiffy6969** [comment]
So this is a complex issue, it requires engine support to enable mutable arrays..... For now I will see if I can get by some other way, or maybe a dirty checking solution to fall back on for other browsers. This is closed thanks.

**Comment by samthor** [comment]
I'm sorry the polyfill hasn't worked for you. It's really a limited set of operations and I'll try to make that clearer in the README. Dirty checking will work, yes, but it's slow as you're no doubt aware :(

**Comment by smiffy6969** [comment]
thats fine. I should have read the readme a bit better. typical man though, instructions later.... On the plus side I have dropped back to an object.observe polyfill and pretty much have what I need, OO polyfill for when Proxy not present. Just need to tweak it a bit. I have no issue using OO polyfill, as soon as proxy is available it will stop using it. I am only really interested in N-1 anyway. thanks for you help.

Paul

**Comment by alansouzati** [comment]
Hey I'm facing this problem too. I'm trying to use this Polyfill mainly for IE11 that does not support Proxy. and the bundled dependency has the backtick string. IE11 does not support that. So any change that you can use something to transpile that? Or do not use backtick? I would be happy to send a contribution if you guys believe this makes sense.

**Comment by samthor** [comment]
Please use proxy.min.js, which is included in the repo. It's safe for es5.
